-- Acoes de auditoria de comissao, meta e relatorio.
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'COMMISSION_RULE_CREATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'COMMISSION_RULE_END';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'GOAL_CREATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'GOAL_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REPORT_VIEW';
