-- Acoes de auditoria de garantia, certificado, troca e assistencia.
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WARRANTY_ISSUE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WARRANTY_CLAIM';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WARRANTY_VOID';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CERTIFICATE_ISSUE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CERTIFICATE_REISSUE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SALE_RETURN';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SERVICE_ORDER_CREATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SERVICE_ORDER_UPDATE';
