-- Acoes de auditoria de cliente, caixa e venda.
-- Migracao separada: o Postgres nao permite usar um valor de enum na mesma
-- transacao em que ele e adicionado.
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CUSTOMER_CREATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CUSTOMER_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CASH_OPEN';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CASH_CLOSE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CASH_WITHDRAWAL';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CASH_SUPPLY';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SALE_COMPLETE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SALE_CANCEL';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SALE_DISCOUNT_AUTHORIZED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'RESERVATION_CREATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'RESERVATION_CANCEL';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'RESERVATION_CONVERT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'QUOTE_CREATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'QUOTE_CONVERT';
