-- Acoes de auditoria do catalogo e do estoque.
--
-- Migracao separada da que criou as tabelas de proposito: o Postgres nao
-- permite usar um valor de enum na mesma transacao em que ele e adicionado.
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CATEGORY_CREATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CATEGORY_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRODUCT_CREATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRODUCT_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRODUCT_DEACTIVATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRODUCT_PRICE_CHANGE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STOCK_MOVEMENT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STOCK_ADJUST';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STOCK_TRANSFER_CREATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STOCK_TRANSFER_SEND';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STOCK_TRANSFER_RECEIVE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STOCK_TRANSFER_CANCEL';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'INVENTORY_OPEN';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'INVENTORY_COUNT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'INVENTORY_CLOSE';
